name: Multi-Platform Matrix Build with Artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build for Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14, 16, 18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: matrix-2d48281
        run: echo "Building for Node version ${{ matrix.node }}"

      - name: Generate build artifact
        run: |
          echo "This is the build output for Node version ${{ matrix.node }}" > build-output-${{ matrix.node }}.txt
          echo "Generated on $(date)" >> build-output-${{ matrix.node }}.txt
          cat build-output-${{ matrix.node }}.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-2d48281-v${{ matrix.node }}
          path: build-output-${{ matrix.node }}.txt
